title: flopska.com/blog
about: "Computer science student, boulderer and free climber. Writing code in Java and Ruby."
twitterurl: "https://twitter.com/flopska"
githuburl: "https://github.com/flopska"

markdown: rdiscount
pygments: true

baseurl: 
# baseurl: /blog

relative_permalinks: true
permalink:   /:year/:title/
host:        0.0.0.0
port:        4000
# url:         http://localhost:4000
url: http://flopska.com/blog

exclude: ['*.scss', 'config.codekit', 'Gemfile', 'Gemfile.lock', 'Guardfile', 'vendor', 'css/bourbon', 'css/neat' ]

highlighter: pygments
